version: 1.2
workflows:
  - name: GTEx-RNAseq-FASTQ
    description: GTEx RNAseq pipeline for FASTQ input
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/GTEx-RNAseq_fastq.wdl
    authors:
      - name: Garrett Lam
        email: glam@broadinstitute.org
  
  - name: GTEx-RNAseq-BAM
    description: GTEx RNAseq pipeline for BAM input
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/GTEx-RNAseq_bam.wdl
    authors:
      - name: Garrett Lam
        email: glam@broadinstitute.org
  
  - name: GenerateSTARIndex
    description: Workflow to generate a STAR genome index
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/generate_star_index.wdl
    authors:
      - name: Garrett Lam
        email: glam@broadinstitute.org
  
  - name: GenerateRSEMReference
    description: Workflow to generate RSEM reference
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/generate_rsem_reference.wdl
    authors:
      - name: Garrett Lam
        email: glam@broadinstitute.org
  
  - name: samtools_idx
    description: Workflow to index BAM files using samtools
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/samtools_idx.wdl
    authors:
      - name: Garrett Lam
        email: glam@broadinstitute.org