version: 1.2
workflows:
  - name: GTEx-RNAseq-FASTQ
    description: GTEx RNAseq pipeline for FASTQ input
    subclass: WDL
    primaryDescriptorPath: GTEx-RNAseq.wdl
  
  - name: GTEx-RNAseq-BAM
    description: GTEx RNAseq pipeline for BAM input
    subclass: WDL
    primaryDescriptorPath: GTEx-RNAseq_bam.wdl