version: 1.2
workflows:
  - name: GTEx-RNAseq
    subclass: WDL
    primaryDescriptorPath: /GTEx-RNAseq.wdl
        authors:
            - name: Garrett Lam
              email: glam@broadinstitute.org